# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6122c100f4121c5d68a0e8c061c9e855d0c6657842b4de315763b02ad7b75c399d18c539a0a729d74dd40f5b0cb92002be8fcda7fe1d0af894557270fcb0811b

test:
  secret_key_base: aeaa3b9723debbb73d7b13bcdb6e2f0b4dc427920b52c94258376e1960e4abed6cd5eb9d5bef0719cc58ee1417952b43dbf82af144156e39c9995fb7529b2187

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
